root: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

env:
  es2023: true
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  project:
    - tsconfig.json

settings:
  import/resolver: typescript

rules:
  no-console: off
  import/extensions:
    - error
    - ts: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - prisma/**/*.ts
  import/order:
    - warn
    - newlines-between: always
  import/prefer-default-export: off
